name = "PhaseGN"
uuid = "bbb8cc82-cd35-478e-9dcb-abc9b4aaacf4"
version = "0.1.0"
authors = ["biplab37 <biplabmahato37@gmail.com>"]

[deps]
AdaptiveSparseGrids = "676d8d29-539e-4f06-b848-7dd647dd5291"
Cubature = "667455a9-e2ce-5579-9412-b964f529a492"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Interpolations = "a98d9a8b-a2ab-59e6-89dd-64a1c18fca59"
NLsolve = "2774e3e8-f4cf-5e23-947b-6d7e65073b56"
PolyLog = "85e3b03c-9856-11eb-0374-4dc1f8670e7f"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
UsefulFunctions = "3faa5a7b-8411-4986-9283-d50561d89da5"

[compat]
AdaptiveSparseGrids = "0.3.0"
Interpolations = "0.16.2"
